### GET measures. Devuelve todas las medidas del POI y de los inversores
GET http://127.0.0.1:8000/measures
Content-Type: application/json

### POST setpoints. Con esta petición cambiamos la potencia activa o reactiva de referencia. 
POST http://10.0.0.10:8000/setpoints
Content-Type: application/json

{
    "p_s_ref_BESS" : 0,
    "ramp_bess": 25
}

# 0.9999845947001552
### POST setpoints. Con esta petición cambiamos la potencia activa o reactiva de referencia. 
POST http://localhost:8000/setpoints
Content-Type: application/json

{
    "q_s_ppc_LV0101" : 1.0,
    "q_s_ppc_LV0102" : 1.0,
    "q_s_ref_BESS" : 1
}

### POST setpoints. Con esta petición cambiamos la potencia activa o reactiva de referencia. 
POST http://10.0.0.10:8000/setpoints
Content-Type: application/json

{
    "p_s_ppc_LV0101" : 0,
    "p_s_ppc_LV0102" : 1,
    "q_s_ppc_LV0103" : 1,
    "q_s_ppc_LV0104" : -1,
    "q_s_ppc_LV0201" : -1,
    "q_s_ppc_LV0202" : -1,
    "q_s_ppc_LV0203" : -1,
    "q_s_ppc_LV0204" : -1,
    "q_s_ppc_LV0304" : -1,
    "q_s_ppc_LV0405" : -1,
    "q_s_ppc_LV0401" : -1
}

### POST Con este cambiamos la "irradiancia" realmente limitamos 
POST http://10.0.0.10:8000/irrad
Content-Type: application/json

{
    "irrad_LV0101": 1,
    "irrad_LV0102": 1,
    "irrad_LV0103": 1,
    "irrad_LV0104": 1,
    "irrad_LV0105": 1,
    "irrad_LV0201": 1,
    "irrad_LV0202": 1,
    "irrad_LV0203": 1,
    "irrad_LV0204": 1,
    "irrad_LV0205": 1,
    "irrad_LV0301": 1,
    "irrad_LV0302": 1,
    "irrad_LV0303": 1,
    "irrad_LV0304": 1,
    "irrad_LV0305": 1,
    "irrad_LV0401": 1,
    "irrad_LV0402": 1,
    "irrad_LV0403": 1,
    "irrad_LV0404": 1,
    "irrad_LV0405": 1
}


### Change the response of the inverters
POST http://localhost:8000/response_inverters
Content-Type: application/json

{
    "T_lp1": 0.05,
    "T_lp2": 0.05,
    "PRamp": 10,
    "QRamp": 10
}

### GET Nos devuelve la "irradiancia" de cada inversor.
GET http://localhost:8000/irrad

### V_ref_grid
POST http://localhost:8000/set_value
Content-Type: application/json

{
    "name": "v_ref_GRID",
    "value": 0.82
}


### GET Accede al método get_value
GET http://10.0.0.10:8000/get_value
Content-Type: application/json

{
    "name": "i_sr_ref_LV0101"
}

### POST Accede al método set_value
POST http://localhost:8000/set_value
Content-Type: application/json

{
    "name": "i_sr_ref_LV0101",
    "value": 1
}


### GET dimensions
GET http://localhost:8000/dimensions

